version: '3.8'

services:
  postgres:
    image: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=ub
      - POSTGRES_USER=${DB_UB_USER}
      - POSTGRES_PASSWORD=${DB_UB_PWD}
    volumes:
      - baseledger-db:/var/lib/postgresql/data
    networks:
      - baseledger
    hostname: postgres-local-node
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    restart: always
  nats:
    image: nats
    command: ["--auth", "testToken1", "-DV"]
    hostname:
      nats-local-node
    networks:
      - baseledger
    ports:
      - ${NATS_EXPOSED_PORT}:4222
    restart: always
  blockchain_app:
    build:
      context: ../../blockchain_app
      dockerfile: ../blockchain_app/ops/Dockerfile
    image: blockchain_app
    # container_name: ${prefix}-staport // TODO: Use this instead of -p first_node to avoid number suffix
    networks:
      - baseledger
    ports:
      - ${BLOCKCHAIN_APP_API_PORT}:1317
      - ${TENDERMINT_NODE_PORT}:26656
      - ${TENDERMINT_NODE_GRPC_PORT}:26657
    extra_hosts:
        - "host.docker.internal:host-gateway" # enable targeting host machine with host.docker.internal
  proxy_app:
    build:
      context: ../../proxy_app
      dockerfile: ../proxy_app/ops/Dockerfile
      args:
        - DB_HOST=postgres-local-node
    image: proxy_app
    environment:
      - ORGANIZATION_ID=${ORGANIZATION_ID}
      - DB_UB_USER=${DB_UB_USER}
      - DB_UB_PWD=${DB_UB_PWD}
      - API_UB_USER=${API_UB_USER}
      - API_UB_PWD=${API_UB_PWD}
      - SWAGGER_HOST=localhost:${PROXY_APP_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - baseledger
    ports:
      - ${PROXY_APP_PORT}:8080
    extra_hosts:
        - "host.docker.internal:host-gateway" # enable targeting host machine with host.docker.internal
    depends_on:
        - postgres
        - nats

networks:
  baseledger:
    driver: bridge

volumes:
  baseledger-db:    