// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trustmesh/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetSynchronizationFeedbackRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSynchronizationFeedbackRequest) Reset() {
	*m = QueryGetSynchronizationFeedbackRequest{}
}
func (m *QueryGetSynchronizationFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSynchronizationFeedbackRequest) ProtoMessage()    {}
func (*QueryGetSynchronizationFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{0}
}
func (m *QueryGetSynchronizationFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSynchronizationFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSynchronizationFeedbackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSynchronizationFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSynchronizationFeedbackRequest.Merge(m, src)
}
func (m *QueryGetSynchronizationFeedbackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSynchronizationFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSynchronizationFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSynchronizationFeedbackRequest proto.InternalMessageInfo

func (m *QueryGetSynchronizationFeedbackRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetSynchronizationFeedbackResponse struct {
	SynchronizationFeedback *SynchronizationFeedback `protobuf:"bytes,1,opt,name=SynchronizationFeedback,proto3" json:"SynchronizationFeedback,omitempty"`
}

func (m *QueryGetSynchronizationFeedbackResponse) Reset() {
	*m = QueryGetSynchronizationFeedbackResponse{}
}
func (m *QueryGetSynchronizationFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSynchronizationFeedbackResponse) ProtoMessage()    {}
func (*QueryGetSynchronizationFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{1}
}
func (m *QueryGetSynchronizationFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSynchronizationFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSynchronizationFeedbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSynchronizationFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSynchronizationFeedbackResponse.Merge(m, src)
}
func (m *QueryGetSynchronizationFeedbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSynchronizationFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSynchronizationFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSynchronizationFeedbackResponse proto.InternalMessageInfo

func (m *QueryGetSynchronizationFeedbackResponse) GetSynchronizationFeedback() *SynchronizationFeedback {
	if m != nil {
		return m.SynchronizationFeedback
	}
	return nil
}

type QueryAllSynchronizationFeedbackRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSynchronizationFeedbackRequest) Reset() {
	*m = QueryAllSynchronizationFeedbackRequest{}
}
func (m *QueryAllSynchronizationFeedbackRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSynchronizationFeedbackRequest) ProtoMessage()    {}
func (*QueryAllSynchronizationFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{2}
}
func (m *QueryAllSynchronizationFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSynchronizationFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSynchronizationFeedbackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSynchronizationFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSynchronizationFeedbackRequest.Merge(m, src)
}
func (m *QueryAllSynchronizationFeedbackRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSynchronizationFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSynchronizationFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSynchronizationFeedbackRequest proto.InternalMessageInfo

func (m *QueryAllSynchronizationFeedbackRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSynchronizationFeedbackResponse struct {
	SynchronizationFeedback []*SynchronizationFeedback `protobuf:"bytes,1,rep,name=SynchronizationFeedback,proto3" json:"SynchronizationFeedback,omitempty"`
	Pagination              *query.PageResponse        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSynchronizationFeedbackResponse) Reset() {
	*m = QueryAllSynchronizationFeedbackResponse{}
}
func (m *QueryAllSynchronizationFeedbackResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSynchronizationFeedbackResponse) ProtoMessage()    {}
func (*QueryAllSynchronizationFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{3}
}
func (m *QueryAllSynchronizationFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSynchronizationFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSynchronizationFeedbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSynchronizationFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSynchronizationFeedbackResponse.Merge(m, src)
}
func (m *QueryAllSynchronizationFeedbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSynchronizationFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSynchronizationFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSynchronizationFeedbackResponse proto.InternalMessageInfo

func (m *QueryAllSynchronizationFeedbackResponse) GetSynchronizationFeedback() []*SynchronizationFeedback {
	if m != nil {
		return m.SynchronizationFeedback
	}
	return nil
}

func (m *QueryAllSynchronizationFeedbackResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetSynchronizationRequestRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetSynchronizationRequestRequest) Reset()         { *m = QueryGetSynchronizationRequestRequest{} }
func (m *QueryGetSynchronizationRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSynchronizationRequestRequest) ProtoMessage()    {}
func (*QueryGetSynchronizationRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{4}
}
func (m *QueryGetSynchronizationRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSynchronizationRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSynchronizationRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSynchronizationRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSynchronizationRequestRequest.Merge(m, src)
}
func (m *QueryGetSynchronizationRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSynchronizationRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSynchronizationRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSynchronizationRequestRequest proto.InternalMessageInfo

func (m *QueryGetSynchronizationRequestRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetSynchronizationRequestResponse struct {
	SynchronizationRequest *SynchronizationRequest `protobuf:"bytes,1,opt,name=SynchronizationRequest,proto3" json:"SynchronizationRequest,omitempty"`
}

func (m *QueryGetSynchronizationRequestResponse) Reset() {
	*m = QueryGetSynchronizationRequestResponse{}
}
func (m *QueryGetSynchronizationRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSynchronizationRequestResponse) ProtoMessage()    {}
func (*QueryGetSynchronizationRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{5}
}
func (m *QueryGetSynchronizationRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSynchronizationRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSynchronizationRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSynchronizationRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSynchronizationRequestResponse.Merge(m, src)
}
func (m *QueryGetSynchronizationRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSynchronizationRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSynchronizationRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSynchronizationRequestResponse proto.InternalMessageInfo

func (m *QueryGetSynchronizationRequestResponse) GetSynchronizationRequest() *SynchronizationRequest {
	if m != nil {
		return m.SynchronizationRequest
	}
	return nil
}

type QueryAllSynchronizationRequestRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSynchronizationRequestRequest) Reset()         { *m = QueryAllSynchronizationRequestRequest{} }
func (m *QueryAllSynchronizationRequestRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSynchronizationRequestRequest) ProtoMessage()    {}
func (*QueryAllSynchronizationRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{6}
}
func (m *QueryAllSynchronizationRequestRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSynchronizationRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSynchronizationRequestRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSynchronizationRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSynchronizationRequestRequest.Merge(m, src)
}
func (m *QueryAllSynchronizationRequestRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSynchronizationRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSynchronizationRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSynchronizationRequestRequest proto.InternalMessageInfo

func (m *QueryAllSynchronizationRequestRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSynchronizationRequestResponse struct {
	SynchronizationRequest []*SynchronizationRequest `protobuf:"bytes,1,rep,name=SynchronizationRequest,proto3" json:"SynchronizationRequest,omitempty"`
	Pagination             *query.PageResponse       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSynchronizationRequestResponse) Reset() {
	*m = QueryAllSynchronizationRequestResponse{}
}
func (m *QueryAllSynchronizationRequestResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSynchronizationRequestResponse) ProtoMessage()    {}
func (*QueryAllSynchronizationRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa4b73ba68f1794a, []int{7}
}
func (m *QueryAllSynchronizationRequestResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSynchronizationRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSynchronizationRequestResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSynchronizationRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSynchronizationRequestResponse.Merge(m, src)
}
func (m *QueryAllSynchronizationRequestResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSynchronizationRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSynchronizationRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSynchronizationRequestResponse proto.InternalMessageInfo

func (m *QueryAllSynchronizationRequestResponse) GetSynchronizationRequest() []*SynchronizationRequest {
	if m != nil {
		return m.SynchronizationRequest
	}
	return nil
}

func (m *QueryAllSynchronizationRequestResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetSynchronizationFeedbackRequest)(nil), "example.baseledger.trustmesh.QueryGetSynchronizationFeedbackRequest")
	proto.RegisterType((*QueryGetSynchronizationFeedbackResponse)(nil), "example.baseledger.trustmesh.QueryGetSynchronizationFeedbackResponse")
	proto.RegisterType((*QueryAllSynchronizationFeedbackRequest)(nil), "example.baseledger.trustmesh.QueryAllSynchronizationFeedbackRequest")
	proto.RegisterType((*QueryAllSynchronizationFeedbackResponse)(nil), "example.baseledger.trustmesh.QueryAllSynchronizationFeedbackResponse")
	proto.RegisterType((*QueryGetSynchronizationRequestRequest)(nil), "example.baseledger.trustmesh.QueryGetSynchronizationRequestRequest")
	proto.RegisterType((*QueryGetSynchronizationRequestResponse)(nil), "example.baseledger.trustmesh.QueryGetSynchronizationRequestResponse")
	proto.RegisterType((*QueryAllSynchronizationRequestRequest)(nil), "example.baseledger.trustmesh.QueryAllSynchronizationRequestRequest")
	proto.RegisterType((*QueryAllSynchronizationRequestResponse)(nil), "example.baseledger.trustmesh.QueryAllSynchronizationRequestResponse")
}

func init() { proto.RegisterFile("trustmesh/query.proto", fileDescriptor_fa4b73ba68f1794a) }

var fileDescriptor_fa4b73ba68f1794a = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x6b, 0x13, 0x41,
	0x1c, 0xc6, 0x3b, 0xa9, 0x2f, 0x30, 0x82, 0x87, 0x01, 0xdf, 0x96, 0xb2, 0xc8, 0x82, 0x89, 0x78,
	0x98, 0xa1, 0xb5, 0xb5, 0xbe, 0xd4, 0x43, 0xda, 0xda, 0xe2, 0x4d, 0xe3, 0xcd, 0xdb, 0x6c, 0xf6,
	0xcf, 0x66, 0x71, 0xb3, 0xb3, 0xdd, 0x99, 0x48, 0xa3, 0x78, 0xf1, 0x13, 0x08, 0x82, 0x07, 0xbf,
	0x84, 0x5f, 0xc3, 0x63, 0xc1, 0x8b, 0x37, 0x25, 0x29, 0x22, 0x7e, 0x0a, 0xc9, 0xec, 0xa4, 0x69,
	0x34, 0x93, 0x4d, 0xb6, 0x39, 0xe7, 0xf9, 0x3f, 0x33, 0xbf, 0xe7, 0xf9, 0x67, 0x58, 0x7c, 0x45,
	0x65, 0x1d, 0xa9, 0xda, 0x20, 0x5b, 0xec, 0xa0, 0x03, 0x59, 0x97, 0xa6, 0x99, 0x50, 0x82, 0xac,
	0xc0, 0x21, 0x6f, 0xa7, 0x31, 0x50, 0x9f, 0x4b, 0x88, 0x21, 0x08, 0x21, 0xa3, 0x27, 0x4a, 0x67,
	0x25, 0x14, 0x22, 0x8c, 0x81, 0xf1, 0x34, 0x62, 0x3c, 0x49, 0x84, 0xe2, 0x2a, 0x12, 0x89, 0xcc,
	0x67, 0x9d, 0x3b, 0x4d, 0x21, 0xdb, 0x42, 0xb2, 0xc1, 0x68, 0x6e, 0xca, 0x5e, 0xaf, 0xfa, 0xa0,
	0xf8, 0x2a, 0x4b, 0x79, 0x18, 0x25, 0x5a, 0x6c, 0xb4, 0xb5, 0xd1, 0xf1, 0x2f, 0xba, 0x49, 0xb3,
	0x95, 0x89, 0x24, 0x7a, 0xa3, 0x05, 0x7b, 0x00, 0x81, 0xcf, 0x9b, 0xaf, 0x8c, 0xb0, 0x6a, 0x15,
	0x36, 0xe0, 0xa0, 0x03, 0x52, 0xe5, 0x3a, 0xef, 0x3e, 0xae, 0x3e, 0x1f, 0x1c, 0xb9, 0x0f, 0xca,
	0x62, 0x68, 0xf4, 0xe4, 0x32, 0xae, 0x44, 0xc1, 0x75, 0x74, 0x13, 0xdd, 0x3e, 0xd7, 0xa8, 0x44,
	0x81, 0xf7, 0x19, 0xe1, 0x5a, 0xe1, 0xa8, 0x4c, 0x45, 0x22, 0x81, 0x08, 0x7c, 0xcd, 0x22, 0xd1,
	0x86, 0x97, 0xd6, 0x36, 0xe8, 0xb4, 0x00, 0xa9, 0xcd, 0xdf, 0xe6, 0xea, 0xa5, 0x06, 0xab, 0x1e,
	0xc7, 0x05, 0x58, 0x7b, 0x18, 0x8f, 0x52, 0x36, 0xb7, 0xa9, 0xd2, 0xbc, 0x12, 0x7d, 0x19, 0x9a,
	0xf7, 0x6c, 0x2a, 0xa1, 0xcf, 0x78, 0x08, 0x66, 0xb6, 0x71, 0x6a, 0xd2, 0xeb, 0x0f, 0xe3, 0x98,
	0x76, 0xe4, 0x2c, 0x71, 0x2c, 0x2f, 0x3e, 0x0e, 0xb2, 0x3f, 0x06, 0x59, 0xd1, 0x90, 0xb5, 0x42,
	0xc8, 0xfc, 0xb6, 0x63, 0x94, 0x9b, 0xf8, 0x96, 0xa5, 0xf3, 0x61, 0x26, 0x96, 0x6d, 0xf9, 0x84,
	0xac, 0x8b, 0x76, 0x32, 0x69, 0xd2, 0x89, 0xf1, 0xd5, 0xc9, 0x0a, 0xd3, 0xce, 0xfa, 0x5c, 0xe1,
	0x0c, 0xdd, 0x2d, 0x9e, 0x9e, 0x30, 0x44, 0xff, 0xd7, 0xf6, 0x0f, 0xd1, 0xa2, 0x16, 0xe5, 0x07,
	0xb2, 0xee, 0xe6, 0x3c, 0x49, 0x2c, 0x2f, 0x3a, 0x89, 0x85, 0x2d, 0xc9, 0xda, 0x97, 0x8b, 0xf8,
	0xbc, 0x26, 0x24, 0x7f, 0x90, 0x75, 0xd3, 0xc9, 0xee, 0xf4, 0xcb, 0xcf, 0xf6, 0x2a, 0x39, 0x4f,
	0xce, 0xe8, 0x92, 0x5f, 0xdf, 0xdb, 0x7e, 0xff, 0xed, 0xf8, 0x63, 0x65, 0x8b, 0x3c, 0x64, 0xc6,
	0x8e, 0x8d, 0xec, 0x58, 0xe1, 0x9b, 0xcb, 0xde, 0x46, 0xc1, 0x3b, 0xf2, 0x1b, 0x61, 0xc7, 0x22,
	0xa8, 0xc7, 0xf1, 0x4c, 0xbc, 0x85, 0xcf, 0xd5, 0x4c, 0xbc, 0xc5, 0x2f, 0x90, 0xf7, 0x58, 0xf3,
	0x6e, 0x92, 0x8d, 0x52, 0xbc, 0xe4, 0x17, 0xb2, 0x6d, 0x26, 0xd9, 0x29, 0x55, 0xc8, 0xf8, 0x7f,
	0xcd, 0xd9, 0x3d, 0x9b, 0x89, 0x81, 0xac, 0x6b, 0xc8, 0x47, 0xe4, 0xc1, 0x5c, 0x90, 0xc6, 0x25,
	0xef, 0xf4, 0x18, 0xe1, 0x1b, 0x93, 0x7f, 0x1f, 0x54, 0xba, 0x53, 0xaa, 0x8c, 0x12, 0xac, 0x85,
	0x4f, 0x85, 0xb7, 0xa5, 0x59, 0xef, 0x91, 0xf5, 0x32, 0xac, 0xdb, 0x4f, 0xbf, 0xf6, 0x5c, 0x74,
	0xd4, 0x73, 0xd1, 0xcf, 0x9e, 0x8b, 0x3e, 0xf4, 0xdd, 0xa5, 0xa3, 0xbe, 0xbb, 0xf4, 0xbd, 0xef,
	0x2e, 0xbd, 0x64, 0x61, 0xa4, 0x5a, 0x1d, 0x9f, 0x36, 0x45, 0x7b, 0x92, 0xf3, 0xe1, 0x29, 0x6f,
	0xd5, 0x4d, 0x41, 0xfa, 0x17, 0xf4, 0x77, 0xc5, 0xdd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64,
	0xab, 0x15, 0xab, 0x29, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	SynchronizationFeedback(ctx context.Context, in *QueryGetSynchronizationFeedbackRequest, opts ...grpc.CallOption) (*QueryGetSynchronizationFeedbackResponse, error)
	SynchronizationFeedbackAll(ctx context.Context, in *QueryAllSynchronizationFeedbackRequest, opts ...grpc.CallOption) (*QueryAllSynchronizationFeedbackResponse, error)
	SynchronizationRequest(ctx context.Context, in *QueryGetSynchronizationRequestRequest, opts ...grpc.CallOption) (*QueryGetSynchronizationRequestResponse, error)
	SynchronizationRequestAll(ctx context.Context, in *QueryAllSynchronizationRequestRequest, opts ...grpc.CallOption) (*QueryAllSynchronizationRequestResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) SynchronizationFeedback(ctx context.Context, in *QueryGetSynchronizationFeedbackRequest, opts ...grpc.CallOption) (*QueryGetSynchronizationFeedbackResponse, error) {
	out := new(QueryGetSynchronizationFeedbackResponse)
	err := c.cc.Invoke(ctx, "/example.baseledger.trustmesh.Query/SynchronizationFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SynchronizationFeedbackAll(ctx context.Context, in *QueryAllSynchronizationFeedbackRequest, opts ...grpc.CallOption) (*QueryAllSynchronizationFeedbackResponse, error) {
	out := new(QueryAllSynchronizationFeedbackResponse)
	err := c.cc.Invoke(ctx, "/example.baseledger.trustmesh.Query/SynchronizationFeedbackAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SynchronizationRequest(ctx context.Context, in *QueryGetSynchronizationRequestRequest, opts ...grpc.CallOption) (*QueryGetSynchronizationRequestResponse, error) {
	out := new(QueryGetSynchronizationRequestResponse)
	err := c.cc.Invoke(ctx, "/example.baseledger.trustmesh.Query/SynchronizationRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SynchronizationRequestAll(ctx context.Context, in *QueryAllSynchronizationRequestRequest, opts ...grpc.CallOption) (*QueryAllSynchronizationRequestResponse, error) {
	out := new(QueryAllSynchronizationRequestResponse)
	err := c.cc.Invoke(ctx, "/example.baseledger.trustmesh.Query/SynchronizationRequestAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	SynchronizationFeedback(context.Context, *QueryGetSynchronizationFeedbackRequest) (*QueryGetSynchronizationFeedbackResponse, error)
	SynchronizationFeedbackAll(context.Context, *QueryAllSynchronizationFeedbackRequest) (*QueryAllSynchronizationFeedbackResponse, error)
	SynchronizationRequest(context.Context, *QueryGetSynchronizationRequestRequest) (*QueryGetSynchronizationRequestResponse, error)
	SynchronizationRequestAll(context.Context, *QueryAllSynchronizationRequestRequest) (*QueryAllSynchronizationRequestResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) SynchronizationFeedback(ctx context.Context, req *QueryGetSynchronizationFeedbackRequest) (*QueryGetSynchronizationFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizationFeedback not implemented")
}
func (*UnimplementedQueryServer) SynchronizationFeedbackAll(ctx context.Context, req *QueryAllSynchronizationFeedbackRequest) (*QueryAllSynchronizationFeedbackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizationFeedbackAll not implemented")
}
func (*UnimplementedQueryServer) SynchronizationRequest(ctx context.Context, req *QueryGetSynchronizationRequestRequest) (*QueryGetSynchronizationRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizationRequest not implemented")
}
func (*UnimplementedQueryServer) SynchronizationRequestAll(ctx context.Context, req *QueryAllSynchronizationRequestRequest) (*QueryAllSynchronizationRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SynchronizationRequestAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_SynchronizationFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSynchronizationFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SynchronizationFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.baseledger.trustmesh.Query/SynchronizationFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SynchronizationFeedback(ctx, req.(*QueryGetSynchronizationFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SynchronizationFeedbackAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSynchronizationFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SynchronizationFeedbackAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.baseledger.trustmesh.Query/SynchronizationFeedbackAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SynchronizationFeedbackAll(ctx, req.(*QueryAllSynchronizationFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SynchronizationRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSynchronizationRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SynchronizationRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.baseledger.trustmesh.Query/SynchronizationRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SynchronizationRequest(ctx, req.(*QueryGetSynchronizationRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SynchronizationRequestAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSynchronizationRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SynchronizationRequestAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.baseledger.trustmesh.Query/SynchronizationRequestAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SynchronizationRequestAll(ctx, req.(*QueryAllSynchronizationRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.baseledger.trustmesh.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SynchronizationFeedback",
			Handler:    _Query_SynchronizationFeedback_Handler,
		},
		{
			MethodName: "SynchronizationFeedbackAll",
			Handler:    _Query_SynchronizationFeedbackAll_Handler,
		},
		{
			MethodName: "SynchronizationRequest",
			Handler:    _Query_SynchronizationRequest_Handler,
		},
		{
			MethodName: "SynchronizationRequestAll",
			Handler:    _Query_SynchronizationRequestAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trustmesh/query.proto",
}

func (m *QueryGetSynchronizationFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSynchronizationFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSynchronizationFeedbackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSynchronizationFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSynchronizationFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSynchronizationFeedbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SynchronizationFeedback != nil {
		{
			size, err := m.SynchronizationFeedback.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSynchronizationFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSynchronizationFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSynchronizationFeedbackRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSynchronizationFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSynchronizationFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSynchronizationFeedbackResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SynchronizationFeedback) > 0 {
		for iNdEx := len(m.SynchronizationFeedback) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SynchronizationFeedback[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSynchronizationRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSynchronizationRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSynchronizationRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSynchronizationRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSynchronizationRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSynchronizationRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SynchronizationRequest != nil {
		{
			size, err := m.SynchronizationRequest.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSynchronizationRequestRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSynchronizationRequestRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSynchronizationRequestRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSynchronizationRequestResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSynchronizationRequestResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSynchronizationRequestResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.SynchronizationRequest) > 0 {
		for iNdEx := len(m.SynchronizationRequest) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SynchronizationRequest[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetSynchronizationFeedbackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetSynchronizationFeedbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SynchronizationFeedback != nil {
		l = m.SynchronizationFeedback.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSynchronizationFeedbackRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSynchronizationFeedbackResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SynchronizationFeedback) > 0 {
		for _, e := range m.SynchronizationFeedback {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSynchronizationRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetSynchronizationRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SynchronizationRequest != nil {
		l = m.SynchronizationRequest.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSynchronizationRequestRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSynchronizationRequestResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SynchronizationRequest) > 0 {
		for _, e := range m.SynchronizationRequest {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetSynchronizationFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSynchronizationFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSynchronizationFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSynchronizationFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSynchronizationFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSynchronizationFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SynchronizationFeedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SynchronizationFeedback == nil {
				m.SynchronizationFeedback = &SynchronizationFeedback{}
			}
			if err := m.SynchronizationFeedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSynchronizationFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSynchronizationFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSynchronizationFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSynchronizationFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSynchronizationFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSynchronizationFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SynchronizationFeedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SynchronizationFeedback = append(m.SynchronizationFeedback, &SynchronizationFeedback{})
			if err := m.SynchronizationFeedback[len(m.SynchronizationFeedback)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSynchronizationRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSynchronizationRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSynchronizationRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSynchronizationRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSynchronizationRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSynchronizationRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SynchronizationRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SynchronizationRequest == nil {
				m.SynchronizationRequest = &SynchronizationRequest{}
			}
			if err := m.SynchronizationRequest.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSynchronizationRequestRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSynchronizationRequestRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSynchronizationRequestRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSynchronizationRequestResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSynchronizationRequestResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSynchronizationRequestResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SynchronizationRequest", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SynchronizationRequest = append(m.SynchronizationRequest, &SynchronizationRequest{})
			if err := m.SynchronizationRequest[len(m.SynchronizationRequest)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
