version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_DB=ub
      - POSTGRES_USER=ub
      - POSTGRES_PASSWORD=ub123
    hostname:
      postgres
    volumes:
      - baseledger-db:/var/lib/postgresql/data
    networks:
      - baseledger
    ports:
      - 5432:5432
    restart: always
  nats:
    image: nats
    container_name: nats
    environment:
      - NATS_USER=bla
    hostname:
      nats
    networks:
      - baseledger
    ports:
      - 4222:4222 
    restart: always
  # starport:
  #     # build: <starport dockerfile>
  #     image: starport/cli
  #     command: ["serve"]
  #     container_name: starport
  #     volumes:
  #       - ../:/apps
  #     working_dir: /apps
  #     hostname:
  #       starport
  #     networks:
  #       - baseledger
  #     ports:
  #       - 1317:1317
  #       - 26657:26657
  #     restart: always

networks:
  baseledger:
    driver: bridge
    ipam:
      config:
      - subnet: 172.40.0.0/24

volumes:
  baseledger-db:
    